base_dns_domain: karmalabs.corp
api_vip: 192.168.129.251
ingress_vip: 192.168.129.250
bmc_user: admin
bmc_password: password
hosts:
- name: ci-ai-node-0
  bmc_url: http://192.168.122.1:9000/redfish/v1/Systems/local/ci-ai-node-0
- name: ci-ai-node-1
  bmc_url: http://192.168.122.1:9000/redfish/v1/Systems/local/ci-ai-node-1
- name: ci-ai-node-2
  bmc_url: http://192.168.122.1:9000/redfish/v1/Systems/local/ci-ai-node-2
