apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: test-agent-cluster-install
  namespace: cluster0
spec:
  apiVIP: %(api_ip)s
  ingressVIP: %(ingress_ip)s
  clusterDeploymentRef:
    name: %(cluster)s
  imageSetRef:
    name: openshift
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    serviceNetwork:
    - 172.30.0.0/16
  provisionRequirements:
    controlPlaneAgents: 3
    workerAgents: 0
  sshPublicKey: %(ssh_public_key)s
