name: nightly-ci-scale

on:
   schedule:
    - cron: '21 2 * * *'

env:
 HOME: /root
 PYTHONUNBUFFERED: true
 CLUSTER: ci-ai
 NODES: 3
 PULLSECRET: /root/openshift_pull.json
 PARAMFILE: .github/scale_parameters.yml
 PLANFILE: .github/kcli_plan.yml
 AI_OFFLINETOKEN: ${{ secrets.AI_OFFLINETOKEN }}

jobs:
    requirements:
      runs-on: libvirt
      steps:
       - uses: actions/checkout@v2
       - run: git pull origin ${GITHUB_REF##*/}
       - name: Install kcli
         run: |
           curl https://raw.githubusercontent.com/karmab/kcli/master/install.sh | bash
           kcli create sushy-service
       - name: Install aicli
         run: |
           pip3 install -U assisted-service-client
            python3 setup.py build
           python3 setup.py install
       - name: Clean up
         continue-on-error: true
         run: |
           kcli delete iso --yes full.iso || true

    scale-kcli-plan:
      needs: requirements
      runs-on: libvirt
      steps:
      - name: Deploy kcli plan
        run: kcli -C local create plan -f $PLANFILE -P nodes=$(($NODES +2 )) $CLUSTER

    scale-ai-cluster:
      needs: scale-kcli-plan
      runs-on: libvirt
      timeout-minutes: 30
      steps:
      - name: Deploy ai cluster
        run: aicli scale deployment --pf $PARAMFILE -P pull_secret=$PULLSECRET $CLUSTER
